summary: Return all images.

tags:
  - Images

responses:
  200:
    description: "Succesful reponse"
    produces: 
      - application/json
    schema:
      type: array
      items:
        $ref:  "#/definitions/Image"

definitions:
  Image:
    id: Image
    title: Image
    type: object
    properties:
      id:
        type: string
        format: uuid
        example: "637250d6-dc57-4d96-9f8a-2697ca5c55c3"
      namespace:
        type: string
        format: uuid
        example: "https://example.com"
      reference:
        type: string
        format: uuid
        example: "00648c29-eca2-4112-8a1a-4deedb443188"
      data:
        type: byte
        example: "aGVsbG8="
        writeOnly: true
      url:
        type: string
        example: "https://mediark.knowark/media/images/\
          00648c29-eca2-4112-8a1a-4deedb443188.jpg"
        readOnly: true
    required:
      - reference
      - data
